### ISSUE TITLE
About data

### ISSUE THREAD

**Issue by 408550969** [Roni-Lab/MA-rPPG-Video-Toolbox#10]
Hi, in the Abstract, it was mentioned that there is a 79% improvement for the rppg dataset. May I ask if each video segment in the rppg dataset is enhanced once?

**Comment by yahskapar** [comment]
Hi @408550969,

Thanks for your interest in our work - can you elaborate on what you mean by "each video segment in the rppg dataset is enhanced once"? 

After applying motion augmentation to training videos as described in the paper, we don't do any additional post-processing or enhancement. There are various approaches to enhance the visual quality of the video (potentially at the expense of destroying the underlying physiological signals) or condition on the underlying physiological signal (not helpful in cases where you'd want some signal degradation so that you can produce more robust models). We don't take any of those approaches and simply feed the motion-augmented outputs (`.npy` files) into the rPPG-Toolbox. Specific details for using this kind of data in that toolbox can be found [here](https://github.com/ubicomplab/rPPG-Toolbox?tab=readme-ov-file#blue_book-motion-augmented-training).

**Comment by 408550969** [comment]
What I mean is that the 79% increase in the introduction is for each RPPG video being augmented once, or for each video being augmented 2-3 times or more? I want to roughly estimate the ratio of motion to stillness in the video
Secondly, I followed the tutorial to run MA and used the command CUDA_VISIBLE-DEVICES=0,1,2,3. However, I found that only GPU0 was used, and most of the time was spent on the CPU during runtime, resulting in low GPU usage. Although 10G of video was generated, it took almost an hour. My video resolution was set to 800 * 650. Is this normal?

**Comment by yahskapar** [comment]
Ah, I see. Each video is only augmented once, though augmenting multiple times could be interesting depending on the types of driving videos used.

Regarding the GPU usage you noted, that does not sound normal, especially if it took you an hour for one video. What kind of GPU(s) do you have? Can you share more details regarding what appears in the terminal as things get setup and start being run by the script? Also, are you using `--mp` to enable multiprocessing?

**Comment by 408550969** [comment]
I have 8 pieces of 4090, and I didn't use -- mp. I used CUDA_VISIBLE_DEVICES=0,1,2,3 python augment_videos.py ... according to the introduction.
Can you provide an example of using -- mp ......?

I am using the default script, but the difference is that I am reading in images instead of videos. I have modified the read_ubfc_video function and the driving function to read videos. For example:
```
def read_ubfc_video(video_file):
    frames = list()
    all_png = sorted(glob.glob(video_file + '/*.png'))
    all_png_sorted = sorted(all_png, key=lambda x: int(x.split('/')[-1].split('.')[0]))
    for png_path in all_png_sorted:
        img = cv2.imread(png_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        frames.append(img)
```

**Comment by 408550969** [comment]
I have 8 pieces of 4090, and I didn't use -- mp. I used CUDA_VISIBLE_DEVICES=0,1,2,3 python augment_videos.py ... according to the introduction.
Can you provide an example of using -- mp ......?

I am using the default script, but the difference is that I am reading in images instead of videos. I have modified the read_ubfc_video function and the driving function to read videos. For example:
```
def read_ubfc_video(video_file):
    frames = list()
    all_png = sorted(glob.glob(video_file + '/*.png'))
    all_png_sorted = sorted(all_png, key=lambda x: int(x.split('/')[-1].split('.')[0]))
    for png_path in all_png_sorted:
        img = cv2.imread(png_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        frames.append(img)
```

**Comment by yahskapar** [comment]
Hi @408550969,

You can simply append `--mp` to the end of your command, for example:
```
python augment_videos.py --config ./checkpoints/checkpoint_new/vox-256-spade.yaml --checkpoint ./checkpoints/checkpoint_new/00000189-checkpoint.pth.tar --source_path /path/to/source/dataset/folder --driving_path /path/to/driving/dataset/folder --augmented_path /path/to/augmented/dataset/folder/to/generate --relative --adapt_scale --dataset UBFC-rPPG --mp
```

Multiprocessing isn't always stable depending on the system, and I will try to make it a bit more robust when I have some downtime, but for your system in particular (which I'm guessing has a reasonable number of CPUs to go with 8x 4090s) it should help a fair bit augmenting videos. Your modification to `read_ubfc_video()` should be fine.

**Comment by 408550969** [comment]
Thanks!
