### ISSUE TITLE
Instructions for Custom Dataset Inferencing

### ISSUE THREAD

**Issue by ss8319** [Roni-Lab/MA-rPPG-Video-Toolbox#11]
Hi,

Thank you for your work.

Would you be able to provide some instructions on how to do inferencing/BPM estimation for private mp4 files using the pretrained model? I dont have the ground truth BVP signals for them only. I only like to perform inferencing without any comparison to the ground truth.

**Comment by yahskapar** [comment]
Hi @ss8319,

Thanks for taking interest in this work. Please check out the [rPPG-Toolbox](https://github.com/ubicomplab/rPPG-Toolbox) to do inference on a custom dataset. You can easily use the pre-trained models in this repo, as well as in the toolbox repo, for inference on any dataset.

If you're having trouble still with custom dataset inference, let's continue the conversation on [this issue of yours](https://github.com/ubicomplab/rPPG-Toolbox/issues/289) in the toolbox repo. As I mentioned there briefly, I think you should try to debug your custom dataloader a bit more.
