### ISSUE TITLE
Can drive full body motion, not just head motion

### ISSUE THREAD

**Issue by zhanghongyong123456** [Roni-Lab/MA-rPPG-Video-Toolbox#8]

**Comment by yahskapar** [comment]
Hi @zhanghongyong123456,

The main, latest version of this repo does not currently support full body motion transfer for rPPG videos that happen to show the full body, but there is some modified code that includes FOMM (First-Order Motion Model) from [here](https://aliaksandrsiarohin.github.io/first-order-model-website/) on this [branch](https://github.com/Roni-Lab/MA-rPPG-Video-Toolbox/tree/FOMM). 

Feel free to read the FOMM paper, take a look at that branch, and then try to transfer full body motion for suitable rPPG videos. I unfortunately do not have time to detail exactly how this would be done outside of sharing the aforementioned branch with you, but if you have any questions feel free to post back here. You can also can check out some more recent methods that also have more explicit usage examples for more than just transferring head motion, for example [this paper](https://snap-research.github.io/unsupervised-volumetric-animation/).

**Comment by zhanghongyong123456** [comment]
> 

I  test  FOMM (First-Order Motion Model)  project,
But this project requires specific data to train a model adapted to specific data，Works poorly for generic data，Did not find a good project to realize portrait full-body drive

**Comment by yahskapar** [comment]
I haven't really worked with FOMM outside of head motion videos, so I can't comment on how well it generalizes outside of results shown in the original paper and from my experience, but maybe give something like the publicly available [articulated motion](https://github.com/snap-research/articulated-animation) repo a shot?

From what I remember from a discussion with a colleague of mine, using the articulated animation method was fairly straightforward when it came to achieving results that did not look awful (though there were still quite a few artifacts). Also fairly easy to train or fine-tune with that method based on the repo instructions. If you're comfortable sharing either here or via email (akshay@cs.unc.edu), I'd be curious to know what the rPPG videos you are working with look like and may be able to give further advice on what could be going wrong once I see them.

**Comment by yahskapar** [comment]
@zhanghongyong123456,

I'll go ahead and close this issue given the lack of further discussion, but please feel free to re-open if needed.
